// Esp32THV.h - Pre-trained Neural Network (ASHRAE Standard 55 based)
// Generated by comfort_nn_trainer.py
//
// NOTE: This neural network was trained on SYNTHETIC data generated using
// ASHRAE Standard 55 acceptable ranges (T: 18-28°C, RH: 30-70%, V: 0.05-0.5 m/s).
// Field validation with real occupant data is planned for future work.

#ifndef ESP32THV_H
#define ESP32THV_H

#include <Arduino.h>

const float INPUT_MEAN[] PROGMEM = {49.954794, 0.497994};
const float INPUT_SCALE[] PROGMEM = {28.907495, 0.315913};

const float OUTPUT_MEAN[] PROGMEM = {22.995479, 49.981918, 0.275203};
const float OUTPUT_SCALE[] PROGMEM = {2.890750, 11.562998, 0.130084};

const float INPUT_HIDDEN_WEIGHTS[] PROGMEM = {
    -0.396696, -0.290870,
    0.464807, 0.001138,
    0.440636, 0.103785,
    -0.078960, -0.014707,
    -0.610424, 0.243705,
    -0.593190, -0.432422,
    -0.307012, -0.224712,
    0.726526, -0.289858,
    -0.000000, -0.000000,
    0.380582, 0.278554,
    -0.720137, -0.171749,
    0.732087, 0.175761,
    0.382929, 0.290818,
    -0.279887, -0.213052,
    -0.574654, 0.228727,
    -0.336540, -0.080836
};

const float HIDDEN_BIAS[] PROGMEM = {
    -0.107146, 0.812578, 0.268735, 0.616126, 0.035104, -0.167971, -0.083043, -0.042125, -0.436433, 0.105926, -0.370228, 0.357164, -0.120345, 0.087341, 0.033406, -0.166758
};

const float HIDDEN_OUTPUT_WEIGHTS[] PROGMEM = {
    0.078772, 0.371864, 0.075993, -0.542211, -0.230595, -0.160953, -0.438543, 0.600344, -0.000000, 0.516983, -0.246732, 0.199047, -0.072973, 0.101868, -0.515271, 0.002047,
    -0.210987, 0.630078, 0.133994, -0.698996, -0.535245, -0.306893, 0.206670, 0.475522, -0.000000, 0.526808, -0.375232, 0.182191, -0.226065, 0.308484, -0.032950, 0.239815,
    0.523550, 0.655934, -0.228148, 0.048866, 0.580976, 0.160115, -0.330418, -0.905028, -0.000000, -0.522753, 0.536603, -0.442272, -0.053020, 0.066407, 0.527645, 0.104123
};

const float OUTPUT_BIAS[] PROGMEM = {
    -0.098013, -0.245401, -0.332739
};

void runNeuralNetwork(float comfort, float feature,
                      float &t_out, float &rh_out, float &v_out);

#endif
